entrypoints Code;

comment "//";
comment "/*" "*/";

Void.           Code            ::= [TopDefinition];

separator nonempty TopDefinition "";

TopDef.         TopDefinition   ::= VisSpec Def;

FunDef.         Def             ::= "fun" Ident "(" [ArgumentDef] ")" OptType FunBody;
VarDef.         Def             ::= VarSpec Ident OptType "=" Exp;
TraitDef.       Def             ::= "trait" Ident TraitArgs TraitBody;

NTraitArgs.     TraitArgs       ::= ;
JTraitArgs.     TraitArgs       ::= "(" [TraitArg] ")";

separator TraitArg ",";
FullTraitArg.   TraitArg        ::= Ident TraitArgCon;

separator Ident ",";

NTraitArgCon.   TraitArgCon     ::= ;
JTraitArgCon.   TraitArgCon     ::= ":" [Ident];

PubSpec.        VisSpec         ::= "public";
PrivSpec.       VisSpec         ::= "private";
DefSpec.        VisSpec         ::= ;

MutSpec.        VarSpec         ::= "var";
ConSpec.        VarSpec         ::= "val";

separator ArgumentDef ",";
ArgDef.         ArgumentDef     ::= Ident ":" Type;

BlockBody.      FunBody         ::= StmtBlock;
ExpBody.        FunBody         ::= "=>" Stmt;

JType.          OptType         ::= ":" Type;
NType.          OptType         ::= ;

separator Type ",";

_.              Type            ::= Type1;
_.              Type1           ::= Type2;
_.              Type2           ::= Type3;

separator Comma "";
CComma.         Comma           ::= ",";

TTrait.         Type            ::= Type1 "(" [Type] ")";
TFunc.          Type            ::= Type1 "->" Type;
TUnion.         Type1           ::= Type2 "|" Type;
TArray.         Type2           ::= Type2 "[" [Comma] "]";
TOptional.      Type2           ::= Type2 "?";
TPointer.       Type2           ::= Type2 "*";
TShared.        Type2           ::= Type2 "@";
TBool.          Type3           ::= "bool";
TInt.           Type3           ::= "int";
TString.        Type3           ::= "string";
TVoid.          Type3           ::= "void";
TNamed.         Type3           ::= Ident;
TTuple.         Type3           ::= "(" [Type] ")";

Block.          StmtBlock       ::= "{" [Stmt] "}";

[].             [Stmt]          ::= ;
(:).            [Stmt]          ::= Stmt "\n" [Stmt];
(:).            [Stmt]          ::= Stmt ";" [Stmt];
SBlock.         Stmt            ::= StmtBlock;
SReturn.        Stmt            ::= "return" OptExp;
SExp.           Stmt            ::= Exp;
SIf.            Stmt            ::= "if" "(" Exp ")" Stmt OptElse;
SWhile.         Stmt            ::= "while" "(" Exp ")" Stmt;
SDoWhile.       Stmt            ::= "do" Stmt "while" "(" Exp ")";
Match.          Stmt            ::= "match" Exp "{" [WithExp] "}";

JElse.          OptElse         ::= "else" Stmt;
NElse.          OptElse         ::= ;

separator WithExp "";
IsCase.         WithExp         ::= "with" Pattern "=>" Stmt;
OtherCase.      WithExp         ::= "else" Stmt;

EPattern.       Pattern         ::= Exp;

JExp.           OptExp          ::= Exp;
NExp.           OptExp          ::= ;

separator nonempty Exp ",";

_.              Exp             ::= Exp1;
_.              Exp1            ::= Exp2;
_.              Exp2            ::= Exp3;

EBinOp.         Exp             ::= Exp1 Op Exp;
EPostOp.        Exp             ::= Exp1 Op;

EPrefOp.        Exp1            ::= Op Exp1;
EIs.            Exp1            ::= Exp2 "is" Pattern;

ECall.          Exp2            ::= Exp2 "(" [ArgVal] ")";
EMember.        Exp2            ::= Exp2 "." Ident;
EElem.          Exp2            ::= Exp2 "[" [Exp] "]";

EInt.           Exp3            ::= Integer;
EString.        Exp3            ::= "\"" [StringChunk] "\"";
ETrue.          Exp3            ::= "true";
EFalse.         Exp3            ::= "false";
EVoid.          Exp3            ::= "void";
EVar.           Exp3            ::= Ident;
ETuple.         Exp3            ::= "(" [Exp] ")";

separator ArgVal ",";

PosArg.         ArgVal          ::= Exp;
NamedArg.       ArgVal          ::= Ident "=" Exp;

separator StringChunk "";

SRaw.           StringChunk     ::= StringText;
SEscape.        StringChunk     ::= EscapeSeq;
SInterp.        StringChunk     ::= "{" Exp "}";

token StringText (char - ["\"\\{}"])+;
token EscapeSeq ({"\\\\"} ["ntr\"\\"]);

token Op ["<>=/^&%$!|-+*@"]+;