entrypoints Code;

comment "//";
comment "/*" "*/";

Void.           Code            ::= [TopDef];

separator nonempty TopDef "";
FunDef.         TopDef          ::= "fun" Ident "(" [ArgumentDef] ")" OptType FunBody;
VarDef.         TopDef          ::= "var" Ident OptType "=" Exp;

separator ArgumentDef ",";
ArgDef.         ArgumentDef     ::= Ident ":" Type;

BlockBody.      FunBody         ::= StmtBlock;
ExpBody.        FunBody         ::= "=>" Stmt;

JType.          OptType         ::= ":" Type;
NType.          OptType         ::= ;

separator Type ",";

_.              Type            ::= Type1;
_.              Type1           ::= Type2;
_.              Type2           ::= Type3;

TFunc.          Type            ::= Type1 "->" Type;
TUnion.         Type1           ::= Type2 "|" Type;
TArray.         Type2           ::= Type2 "[]";
TOptional.      Type2           ::= Type2 "?";
TPointer.       Type2           ::= Type2 "*";
TShared.        Type2           ::= Type2 "@";
TBool.          Type3           ::= "bool";
TInt.           Type3           ::= "int";
TString.        Type3           ::= "string";
TVoid.          Type3           ::= "void";
TNamed.         Type3           ::= Ident;
TTuple.         Type3           ::= "(" [Type] ")";

Block.          StmtBlock       ::= "{" [Stmt] "}";

[].             [Stmt]          ::= ;
(:).            [Stmt]          ::= Stmt "\n" [Stmt];
(:).            [Stmt]          ::= Stmt ";" [Stmt];
SBlock.         Stmt            ::= StmtBlock;
SReturn.        Stmt            ::= "return" OptExp;
SExp.           Stmt            ::= Exp;
SIf.            Stmt            ::= "if" "(" Exp ")" Stmt OptElse;
SWhile.         Stmt            ::= "while" "(" Exp ")" Stmt;
SDoWhile.       Stmt            ::= "do" Stmt "while" "(" Exp ")";
Match.          Stmt            ::= "match" Exp "{" [WithExp] "}";

JElse.          OptElse         ::= "else" Stmt;
NElse.          OptElse         ::= ;

separator WithExp "";
IsCase.         WithExp         ::= "with" Pattern "=>" Stmt;
OtherCase.      WithExp         ::= "else" Stmt;

EPattern.       Pattern         ::= Exp;

JExp.           OptExp          ::= Exp;
NExp.           OptExp          ::= ;

separator nonempty Exp ",";

_.              Exp             ::= Exp1;
_.              Exp1            ::= Exp2;
_.              Exp2            ::= Exp3;
_.              Exp3            ::= Exp4;
EInt.           Exp3            ::= Integer;
EString.        Exp3            ::= String;
ETrue.          Exp3            ::= "true";
EFalse.         Exp3            ::= "false";
EVar.           Exp3            ::= Ident;
ECall.          Exp2            ::= Exp2 "(" [Arg] ")";
EBinOp.         Exp             ::= Exp1 Op Exp;
EPrefOp.        Exp1            ::= Op Exp1;
EPostOp.        Exp             ::= Exp1 Op;
ETuple.         Exp4            ::= "(" [Exp] ")";

separator Arg ",";

EArg.           Arg             ::= Exp;

token Op ["<>=/^&%$!|-+*"]+;