-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language void.

module Void.Abs where

import Prelude (Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

type Code = Code' BNFC'Position
data Code' a = Void a [TopDef' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type TopDef = TopDef' BNFC'Position
data TopDef' a
    = FunDef a Ident [ArgumentDef' a] (Type' a) (FunBody' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type ArgumentDef = ArgumentDef' BNFC'Position
data ArgumentDef' a = ArgDef a Ident (Type' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type FunBody = FunBody' BNFC'Position
data FunBody' a = BlockBody a (StmtBlock' a) | ExpBody a (Stmt' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type ArgType = ArgType' BNFC'Position
data ArgType' a = AType a (Type' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Type = Type' BNFC'Position
data Type' a
    = TBool a
    | TInt a
    | TString a
    | TVoid a
    | TNamed a Ident
    | TArray a (Type' a)
    | TUnion a (Type' a) (Type' a)
    | TFunc a (Type' a) (Type' a)
    | TOptional a (Type' a)
    | TTuple a [Type' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type StmtBlock = StmtBlock' BNFC'Position
data StmtBlock' a = Block a [Stmt' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Stmt = Stmt' BNFC'Position
data Stmt' a
    = SBlock a (StmtBlock' a)
    | SReturn a (Exp' a)
    | SVoidReturn a
    | SExp a (Exp' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Exp = Exp' BNFC'Position
data Exp' a
    = EInt a Integer
    | EString a String
    | ETrue a
    | EFalse a
    | EVar a Ident
    | ECall a (Exp' a) (Exp' a)
    | EBinOp a (Exp' a) Op (Exp' a)
    | EPrefOp a Op (Exp' a)
    | EPostOp a (Exp' a) Op
    | ETuple a [Exp' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype Op = Op String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Code where
  hasPosition = \case
    Void p _ -> p

instance HasPosition TopDef where
  hasPosition = \case
    FunDef p _ _ _ _ -> p

instance HasPosition ArgumentDef where
  hasPosition = \case
    ArgDef p _ _ -> p

instance HasPosition FunBody where
  hasPosition = \case
    BlockBody p _ -> p
    ExpBody p _ -> p

instance HasPosition ArgType where
  hasPosition = \case
    AType p _ -> p

instance HasPosition Type where
  hasPosition = \case
    TBool p -> p
    TInt p -> p
    TString p -> p
    TVoid p -> p
    TNamed p _ -> p
    TArray p _ -> p
    TUnion p _ _ -> p
    TFunc p _ _ -> p
    TOptional p _ -> p
    TTuple p _ -> p

instance HasPosition StmtBlock where
  hasPosition = \case
    Block p _ -> p

instance HasPosition Stmt where
  hasPosition = \case
    SBlock p _ -> p
    SReturn p _ -> p
    SVoidReturn p -> p
    SExp p _ -> p

instance HasPosition Exp where
  hasPosition = \case
    EInt p _ -> p
    EString p _ -> p
    ETrue p -> p
    EFalse p -> p
    EVar p _ -> p
    ECall p _ _ -> p
    EBinOp p _ _ _ -> p
    EPrefOp p _ _ -> p
    EPostOp p _ _ -> p
    ETuple p _ -> p

