-- File generated by the BNF Converter (bnfc 2.9.6.1).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for Void.

module Void.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Void.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Void.Abs.Ident where
  prt _ (Void.Abs.Ident i) = doc $ showString i
instance Print Void.Abs.Op where
  prt _ (Void.Abs.Op i) = doc $ showString i
instance Print (Void.Abs.Code' a) where
  prt i = \case
    Void.Abs.Void _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print [Void.Abs.TopDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Void.Abs.TopDef' a) where
  prt i = \case
    Void.Abs.FunDef _ id_ argumentdefs type_ funbody -> prPrec i 0 (concatD [doc (showString "fun"), prt 0 id_, doc (showString "("), prt 0 argumentdefs, doc (showString ")"), doc (showString ":"), prt 0 type_, prt 0 funbody])

instance Print [Void.Abs.ArgumentDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Void.Abs.ArgumentDef' a) where
  prt i = \case
    Void.Abs.ArgDef _ id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print (Void.Abs.FunBody' a) where
  prt i = \case
    Void.Abs.BlockBody _ stmtblock -> prPrec i 0 (concatD [prt 0 stmtblock])
    Void.Abs.ExpBody _ stmt -> prPrec i 0 (concatD [doc (showString "=>"), prt 0 stmt])

instance Print [Void.Abs.ArgType' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Void.Abs.ArgType' a) where
  prt i = \case
    Void.Abs.AType _ type_ -> prPrec i 0 (concatD [prt 0 type_])

instance Print [Void.Abs.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Void.Abs.Type' a) where
  prt i = \case
    Void.Abs.TBool _ -> prPrec i 3 (concatD [doc (showString "bool")])
    Void.Abs.TInt _ -> prPrec i 3 (concatD [doc (showString "int")])
    Void.Abs.TString _ -> prPrec i 3 (concatD [doc (showString "string")])
    Void.Abs.TVoid _ -> prPrec i 3 (concatD [doc (showString "void")])
    Void.Abs.TNamed _ id_ -> prPrec i 3 (concatD [prt 0 id_])
    Void.Abs.TArray _ type_ -> prPrec i 2 (concatD [prt 2 type_, doc (showString "[]")])
    Void.Abs.TUnion _ type_1 type_2 -> prPrec i 0 (concatD [prt 2 type_1, doc (showString "|"), prt 0 type_2])
    Void.Abs.TFunc _ type_1 type_2 -> prPrec i 1 (concatD [prt 4 type_1, doc (showString "->"), prt 0 type_2])
    Void.Abs.TOptional _ type_ -> prPrec i 1 (concatD [prt 2 type_, doc (showString "?")])
    Void.Abs.TTuple _ types -> prPrec i 4 (concatD [doc (showString "("), prt 0 types, doc (showString ")")])

instance Print (Void.Abs.StmtBlock' a) where
  prt i = \case
    Void.Abs.Block _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [Void.Abs.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print (Void.Abs.Stmt' a) where
  prt i = \case
    Void.Abs.SBlock _ stmtblock -> prPrec i 0 (concatD [prt 0 stmtblock])
    Void.Abs.SReturn _ exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp])
    Void.Abs.SVoidReturn _ -> prPrec i 0 (concatD [doc (showString "return")])
    Void.Abs.SExp _ exp -> prPrec i 0 (concatD [prt 0 exp])

instance Print [Void.Abs.Exp' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Void.Abs.Exp' a) where
  prt i = \case
    Void.Abs.EInt _ n -> prPrec i 3 (concatD [prt 0 n])
    Void.Abs.EString _ str -> prPrec i 3 (concatD [printString str])
    Void.Abs.ETrue _ -> prPrec i 3 (concatD [doc (showString "true")])
    Void.Abs.EFalse _ -> prPrec i 3 (concatD [doc (showString "false")])
    Void.Abs.EVar _ id_ -> prPrec i 3 (concatD [prt 0 id_])
    Void.Abs.ECall _ exp1 exp2 -> prPrec i 2 (concatD [prt 2 exp1, prt 4 exp2])
    Void.Abs.EBinOp _ exp1 op exp2 -> prPrec i 0 (concatD [prt 1 exp1, prt 0 op, prt 0 exp2])
    Void.Abs.EPrefOp _ op exp -> prPrec i 1 (concatD [prt 0 op, prt 1 exp])
    Void.Abs.EPostOp _ exp op -> prPrec i 0 (concatD [prt 1 exp, prt 0 op])
    Void.Abs.ETuple _ exps -> prPrec i 4 (concatD [doc (showString "("), prt 0 exps, doc (showString ")")])
