-- File generated by the BNF Converter (bnfc 2.9.6.1).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module Void.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Void.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Void.Abs.Ident -> Result
transIdent x = case x of
  Void.Abs.Ident string -> failure x

transOp :: Void.Abs.Op -> Result
transOp x = case x of
  Void.Abs.Op string -> failure x

transCode :: Show a => Void.Abs.Code' a -> Result
transCode x = case x of
  Void.Abs.Void _ topdefs -> failure x

transTopDef :: Show a => Void.Abs.TopDef' a -> Result
transTopDef x = case x of
  Void.Abs.FunDef _ ident argumentdefs type_ funbody -> failure x

transArgumentDef :: Show a => Void.Abs.ArgumentDef' a -> Result
transArgumentDef x = case x of
  Void.Abs.ArgDef _ ident type_ -> failure x

transFunBody :: Show a => Void.Abs.FunBody' a -> Result
transFunBody x = case x of
  Void.Abs.BlockBody _ stmtblock -> failure x
  Void.Abs.ExpBody _ stmt -> failure x

transArgType :: Show a => Void.Abs.ArgType' a -> Result
transArgType x = case x of
  Void.Abs.AType _ type_ -> failure x

transType :: Show a => Void.Abs.Type' a -> Result
transType x = case x of
  Void.Abs.TBool _ -> failure x
  Void.Abs.TInt _ -> failure x
  Void.Abs.TString _ -> failure x
  Void.Abs.TVoid _ -> failure x
  Void.Abs.TNamed _ ident -> failure x
  Void.Abs.TArray _ type_ -> failure x
  Void.Abs.TUnion _ type_1 type_2 -> failure x
  Void.Abs.TFunc _ type_1 type_2 -> failure x
  Void.Abs.TOptional _ type_ -> failure x
  Void.Abs.TTuple _ types -> failure x

transStmtBlock :: Show a => Void.Abs.StmtBlock' a -> Result
transStmtBlock x = case x of
  Void.Abs.Block _ stmts -> failure x

transStmt :: Show a => Void.Abs.Stmt' a -> Result
transStmt x = case x of
  Void.Abs.SBlock _ stmtblock -> failure x
  Void.Abs.SReturn _ exp -> failure x
  Void.Abs.SVoidReturn _ -> failure x
  Void.Abs.SExp _ exp -> failure x

transExp :: Show a => Void.Abs.Exp' a -> Result
transExp x = case x of
  Void.Abs.EInt _ integer -> failure x
  Void.Abs.EString _ string -> failure x
  Void.Abs.ETrue _ -> failure x
  Void.Abs.EFalse _ -> failure x
  Void.Abs.EVar _ ident -> failure x
  Void.Abs.ECall _ exp1 exp2 -> failure x
  Void.Abs.EBinOp _ exp1 op exp2 -> failure x
  Void.Abs.EPrefOp _ op exp -> failure x
  Void.Abs.EPostOp _ exp op -> failure x
  Void.Abs.ETuple _ exps -> failure x
